3-5章/vagrant/superbookers/superbookers/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  # この上のやつログイン後？後でチェック

  # git status見ながら正しいURLにくっつけた
  get 'home/about' => 'home#show', as: 'about'
  resources :home, only: [:new, :create, :show]
  # 試しにやってみたが違った。ただあとで使うかもしれないから保留。
  resources :users
  resources :books
  # resource :post_comments, only: [:create]

  post 'books/:id/comment' => 'post_comments#create', as: 'book_post_comments'

  # root :to => 'user#index'
end

3-5章/vagrant/superbookers/superbookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

3-5章/vagrant/superbookers/superbookers/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  has_many :post_comments, dependent: :destroy
end

3-5章/vagrant/superbookers/superbookers/app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

3-5章/vagrant/superbookers/superbookers/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  # 関連づけた。refileの仕様上idという部分を省きました。

  has_many :books, dependent: :destroy
  # Bookモデルは複数形であってる？
  #length: { minimum: 2}
  validates :name, presence: true, length: { in: 2..20 } 
  validates :introduction, length: {maximum: 50}
  has_many :post_comments, dependent: :destroy
end

3-5章/vagrant/superbookers/superbookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    # オンにする必要があるが、リダイレクトされるので一旦解除→再度つけた
    # deviseにまつわる画面で、beforeactionする。（下に定義）
  
  def after_sign_in_path_for(resource)
      user_path(resource)
      # ログイン後ホームではなくマイページに行かせる
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email]) 
    # 新規登録時(sign_up時)にnameというキーのパラメーターを追加で許可する
    # 名前でログインを設定する際に必要
  end
  # 新規登録の際に、nameも入れるようにした。deviseのストロングパラメーターは直接編集できないため、ここに書く！
end

3-5章/vagrant/superbookers/superbookers/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user! 
  # ログインユーザーのみに許可という動作
  before_action :correct_user, only: [:edit, :update]
  # 正しいユーザーのみ、編集とupdateができるということ
  # correct_userは下に定義


  def new
  end
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    # 意味：user_idがnilのままだと、子モデルのbookの方が保存できない
    if @book.save
     flash[:success] = "Book was successfully created."
     redirect_to book_path(@book.id)
   else
    @books = Book.all
    @user = current_user
    render action: :index
    # indexのアクションを無視してインデックスに行く（再定義した理由）／renderの上に書くこと/newもコピペするとミスデータが上書きされる
    end

  end

  def index
    @user = current_user
    # この考えめっちゃ大事(今ログインしているユーザー)
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id]) 
    # このままだと@bookに前のデータが入ってしまう
    @books = Book.all
    # Aさんの全部の本という記述にしたい。自分の投稿一覧の章を見直す

    @user = @book.user
    # 本の投稿者が誰か、本に関連して出す
    @booknew = Book.new


    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id]) 
    # 仮で入力
    render layout: false 
    #application.html.erbを適用したくないときにこの用に書く

    # @book = Book.find(params[:id])
    # データは入っているからいらない
  end

  def update
    @book = Book.find(params[:id])
    # @book.update(book_params)

  if @book.update(book_params)
    flash[:success] = "Book was successfully updated."
    # 成功したらこのメッセージを[:success]のところに出力する
    redirect_to book_path(@book.id)
  else
    render action: :edit
    # updateにはviewがなく,editに書かずここに書いて良い（そのままの画面位もどす）
  end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  # 一覧画面へリダイレクトしたい
  # 文字の表示をインデックスでリダイレクトした後に行いたい 
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
    #データベースからとってくる
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @book = Book.find(params[:id])
    # まず本を取り出した 重要
    @user = @book.user
    # 本に結びついたユーザーを取り出す
    if current_user != @user
      redirect_to books_path
    # 正しいユーザーではない場合本一覧に戻す
    end
  end

end

3-5章/vagrant/superbookers/superbookers/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
  def show
    
  end
end

3-5章/vagrant/superbookers/superbookers/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @book = Book.find(params[:id])
    comment = current_user.post_comments.new(post_comment_params)

    comment.book_id = @book.id
    # @book.user_id = current_user.id　練習

    comment.save
    redirect_to book_path(@book)
  end

private
def post_comment_params
    params.require(:post_comment).permit(:comment)
end

end

3-5章/vagrant/superbookers/superbookers/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ログインしているユーザーのみ・・・意図的に
  before_action :authenticate_user! 
  before_action :correct_user, only: [:edit, :update]
  # 予備：正しいユーザーのみが編集、アップデートできる


  def index
    @user = current_user
    # この考えめっちゃ大事
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
    # urlをもとにユーザーをとってくる
    @book = Book.new
    @books = @user.books
    # 自分の投稿が羅列されるように(ユーザーに関連している本)
  end

  def update
    @user = User.find(params[:id])

  if @user.update(user_params)
    flash[:success] = "User was successfully updated."
    redirect_to user_path(@user.id)
  else
    render action: :edit
  end
  end
  # elseの下に入れると二重になる


  def create
  end

  private 
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    if current_user != @user
       redirect_to user_path(current_user.id)
       # 考える!!userのshow（自分）に行けない、一覧じゃない！
       #paramsだと結局前のやつを参照しちゃう
       #正しい人のIDだからこういう表現になるのだと思う、Railsのメソッド。
    end
  end
end

3-5章/vagrant/superbookers/superbookers/app/helpers/application_helper.rb
module ApplicationHelper
end

3-5章/vagrant/superbookers/superbookers/app/helpers/books_helper.rb
module BooksHelper
end

3-5章/vagrant/superbookers/superbookers/app/helpers/home_helper.rb
module HomeHelper
end

3-5章/vagrant/superbookers/superbookers/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

3-5章/vagrant/superbookers/superbookers/app/helpers/users_helper.rb
module UsersHelper
end

3-5章/vagrant/superbookers/superbookers/app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
<ul>
  <li><%= message %></li>
</ul>

<% end %>
<% end %>
<%# エラーがあればメッセージを出力しますよという意味。.any?は１個でもあれば出る %>

<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
<!-- URLをルートパスにしたい できそう-->
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>  
    <%= link_to "Back" , books_path %>  
    <%= link_to "Show" , book_path %>  
    <%# 一覧に戻れるようにリンクがついている %>
<% end %>

3-5章/vagrant/superbookers/superbookers/app/views/books/index.html.erb
<%= render '/users/show', user: @user,book: @book %>
<!-- 共通部分 -->


<h2>Books</h2>
<div class="col-xs-9">
 <table class="table table-hover table-inverse">
  <!-- ここに登録者一覧を書き出したい →できた-->
  <!-- 画像に「その人の本一覧」＝user/id に行くリンクをつけたい できた！でも、「その投稿した人の」にしないと。→f.user.idでかいけつブックに関連するユーザーに関連するidということ。必ず復習！！！！！！！-->
  <thead>
    <th> </th>
    <th>Title</th>
    <th>Opinion</th>
  </thead>

  <% @books.each do |f| %>
  <tr>
    <td><%= link_to attachment_image_tag(f.user, :profile_image, :fill, 100, 100, 
    # userとは、user_idの略称。なんのモデルを参考にするかの時、「本に関連しているユーザーのプロフィール画像」をださないといけないから@userになっている（重要）
    format: 'jpeg', fallback: "no_image.jpg"),user_path(f.user.id) %></td>
    <!-- .userは、「モデル名（小文字）でデータを参照できる,：データを指定」取り出してくるユーザーのデータは１つしかないから単数形：本に関連するユーザーのIDということ-->
    <td><%= link_to f.title, book_path(f.id) %></td>
    <td><%= f.body %></td>
  </tr>
  <% end %>
</table>
</div>

<%# indexは完全に構造理解(2/11) %>

3-5章/vagrant/superbookers/superbookers/app/views/books/show.html.erb
<% if flash[:success] %>
<div class="flash">
  <%= flash[:success] %>
</div>
<% end %>

<%= render '/users/show', user: @user,book: @booknew %>
<!-- 共有テンプレートは好きなインスタンス変数を入れられる -->

<div class="col-xs-9">
  <h2>Book detail</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </thead>
    <tr>
      <td>
        <%= link_to attachment_image_tag(@user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg"),user_path(@user.id) %><br>
        <%= link_to @user.name, user_path(@user.id) %></td>


      <td><%= link_to @book.title, book_path(@book.id) %></td>
      <td><%= @book.body %></td>

      <% if @user.id == current_user.id %>
      <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
      <td><%= link_to "Destroy", book_path(@book.id) , method: :delete, "data-confirm" => "Are you sure?" %></td>
      <% end %>

    </tr>
  </table>
</div>

<% @book.post_comments.each do |post_comment| %>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %>
  <%= post_comment.comment %>
<% end %>

<a href="#comments"><%= @book.post_comments.count %>件コメント</a>

<%= form_for [@book, @post_comment] do |f| %>

  <%= f.text_area :comment %>
  <%= f.submit "送信する" %>
<% end %>

3-5章/vagrant/superbookers/superbookers/app/views/home/index.html.erb
<% if flash[:notice] %>
<div class="flash">
<%= flash[:notice] %>
</div>
<% end %>

<div class="container">
<div class="row">
<div class="col-md-6 col-md-offset-3">
      <h1>Welcome to <span class="glyphicon glyphicon-book"></span>Bookers!</h1>

      <p>In <span class="glyphicon glyphicon-book"></span>Bookers,<br>
        you can share and exchange your opinions , inpressions , and emotions
      about various books!</p>
    </div>
  </div>

  <div class="row">
    <a class="btn btn-info col-xs-6 col-xs-offset-3 sign_in" href="/users/sign_in">Log in</a>
    <a class="btn btn-success col-xs-6 col-xs-offset-3 sign_up" href="/users/sign_up">Sign Up</a>
  </div>
</div>

3-5章/vagrant/superbookers/superbookers/app/views/home/show.html.erb
<h1>Welcome to <span class="glyphicon glyphicon-book"></span>Bookers!</h1>

3-5章/vagrant/superbookers/superbookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="navbar navbar-inverse">
    <div class="navbar-left text-muted" >
      <h2 class="title">Bookers</h2>
    </div>
    <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
      <% if user_signed_in? %>
      <li class="">
        <%= link_to 'Home', user_path(current_user.id), class: "glyphicon glyphicon-home home" %>
        <!-- 現在ログイン中のってしたい -->
      </li>
      <li class="">
        <%= link_to 'Users', users_path , class: "glyphicon glyphicon-user users" %>
      </li>
      <li class="">
        <%= link_to 'Books', books_path, class: "glyphicon glyphicon-book books"  %>
      </li>
      <li class="">
        <%= link_to "logout", destroy_user_session_path, method: :delete , class: "glyphicon glyphicon-log-out logout" %>
      </li>

      <% else %>
      <li class="">
        <%= link_to "Home", root_path %>
      </li>
      <li class="">
        <%= link_to "About", about_path %>
      </li>      
      <!-- 上二つが仮。ログアウト時のホームと、home/aboutを調べる。 -->
      <li class="">
        <%= link_to "sign up", new_user_registration_path %>
      </li>
      <li class="">
        <%= link_to "Login", new_user_session_path %>
      </li>
      <% end %>
    </ul>
  </div>
  <%= yield %>
  <footer class="col-md-offset-9 col-md-3">CopyRight Infratop.inc</footer>
</body>
</html>

3-5章/vagrant/superbookers/superbookers/app/views/users/_show.html.erb
<% if @book.errors.any? %>
  <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
  <% @book.errors.full_messages.each do |message| %>
<ul>
  <li><%= message %></li>
</ul>

<% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>

      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <%# ユーザーモデルのプロフィールイメージということにできていない？ %>

      <table class="table">
      <thead>
        <th></th>
        <th></th>
      </thead>
        <tr>
          <td>name:</td>
          <td><%= user.name %></td>
        </tr>

        <tr>
          <td>introduction:</td>
          <td><%= user.introduction %></td>
        </tr>


      </table>

      <% if @user.id == current_user.id %>
      <%= link_to " ", edit_user_path(user), class: "btn btn-default glyphicon glyphicon-wrench" %>
      <% end %>

      <h1>New book</h1>
      <%= form_for(book) do |f| %>
      <h4>Title</h4>
      <%= f.text_field :title %>
      <h4>Opinion</h4>
      <%= f.text_area :body %><br>
      <%= f.submit 'Create Book', class: "btn btn-primary" %>
      <!-- ボタンで囲むとサブミットの上についてしまう -->
      <% end %>
    </div>

3-5章/vagrant/superbookers/superbookers/app/views/users/edit.html.erb
<h3>User info(編集ページ)</h3>

<% if @user.errors.any? %>
<h3><%= @user.errors.count %>errors prohibited this book from being saved:</h3>

  <% @user.errors.full_messages.each do |message| %>
<ul>
  <li><%= message %></li>
</ul>

<% end %>
<% end %>

<div class="container">
<%= form_for(@user) do |f| %>
<div class="row">
 <label class="control-label sr-only">Name</label>
 <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
 <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
</div>

<div class="row">
 <div class="user-edit-image">
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
</div>
<label class="control-label sr-only">Image</label><br>
<%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
</div> 

<div class="row">
  <label class="control-label sr-only">introduction</label>
  <%= f.text_field :introduction, autofocus: true, class:"form-control", id:"inputEmail" %>
  <!-- 自己紹介（introduce)を書きたい -->
  <span class="fa fa-user form-control-icon" aria-hidden="true"></span>
</div>

<%= f.submit "Update User", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>

</div>

3-5章/vagrant/superbookers/superbookers/app/views/users/index.html.erb
<% if flash[:success] %>
  <div class="flash">
    <%= flash[:success] %>
  </div>
<% end %>

<%= render '/users/show', user: @user,book: @book %>

<div class="col-xs-9">
  <h1>Users</h1>
  <table class="table table-hover table-inverse">
    <thead>
      <th>image</th>
      <th>name</th>
    </thead>
    <% @users.each do |f| %>
    <tr>
      <td><%= attachment_image_tag f, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
      <!-- .userは、「モデル名（小文字）でデータを参照できる,：データを指定」-->
      <td><%= f.name %></td>
      <td><%=link_to "Show", user_path(f.id) %></td>
      <% end %>
    </tr>
  </div>
</table>

3-5章/vagrant/superbookers/superbookers/app/views/users/show.html.erb
<%= flash[:notice] %>

<% if flash[:success] %>
  <div class="flash">
    <%= flash[:success] %>
  </div>
<% end %>

<%= render '/users/show', user: @user,book: @book %>
<!-- 共通部分 -->

    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <th></th>
          <th>title</th>
          <th>body</th>
        </thead>
        <% @books.each do |f| %>
        <tr>
          <td><%= link_to attachment_image_tag(f.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg"),user_path(f.user.id) %></td>
          <%# 本を出力するのではなく、本と関連したユーザーの画像を出したいから %>
          <!-- .userは、「モデル名（小文字）でデータを参照できる,：データを指定」-->
          <td><%= link_to f.title, book_path(f.id) %></td>
          <td><%= f.body %></td>
          <% end %>
        </tr>
       </table>

      </div>
  </div>
</div>
<!-- ここにも編集じゃなくて詳細リンク繋がないと→OK -->
<%# このファイルも完全理解 %>